# site settings
title: Jonathan da Cruz
subtitle: ... 
email: jonathanadcz@gmail.com
description: Aqui falamos sobre tecnologia, programação e o que mais for necessário!<br /> Um programador aprendendo e compartilhando conhecimentos !
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: 
street_address: 
city: Chapecó
state: SC
zip_code: 89805-000
country: Brasil
phone: (54) 9 96137269

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url: 
instagram_url: https://instagram.com/jonathan_dacruz
linkedin_url: https://www.linkedin.com/in/jonathan-dacruz/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
